name: cookbook
description: App for storing recipes. For now only in English. Beta version.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.2.6
  path_provider: ^2.0.13
  path: ^1.8.2
  dynamic_color: ^1.6.2
  shared_preferences: ^2.0.18
  flutter_speed_dial: ^6.2.0
  image_picker: ^0.8.7
  equatable: ^2.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/appIcon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "dev_assets/appIcon.png"